AWSTemplateFormatVersion: '2010-09-09'
Description: Sample Cloudformation template for launching EC2 instance with unified cloud agent installed
Parameters:
  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Default: test1
  EC2InstanceRole:
    Type: String
    Description: Name of an existing EC2 IAM Role with CloudWatchAgentServerPolicy attached
    Default: EC2RoleForCloudWatchAgent 
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-009d6802948d06e52
      InstanceType: t2.micro
      KeyName: !Ref SSHKey
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroups:
      - !Ref EC2UCWSecurityGroup
      UserData: 
        Fn::Base64: |
            #!/bin/bash -xe
            # Install Httpd server
            sudo yum update -y
            sudo yum install httpd -y
            echo "Thank You! :) ... from $(hostname -f)" > /var/www/html/index.html
            sudo systemctl start httpd
            sudo systemctl enable httpd
            # Install Unified CloudWatch Agent
            wget https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
            sudo rpm -U ./amazon-cloudwatch-agent.rpm
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: CloudWatchAgentDemoInstanceProfile
      Path: "/"
      Roles:
      - !Ref EC2InstanceRole
  EC2UCWSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP accesses on port 22 and 80
      GroupName: ec2-ucw-sg
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: TCP
        ToPort: 22
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: TCP
        ToPort: 80
Outputs:
  MyInstancePublicIp:
    Description: Public IP address of the launch EC2 instance with open SSH port
    Value: !GetAtt MyInstance.PublicIp