AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template
Parameters:
  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The name of the non-cloudformation EC2 KeyPair to enable SSH access to the EC2 instance
    Default: test1
  EC2RoleForCodeDeploy:
    Type: String
    Description: The name of the non-cloudformation EC2 Role to attach to the EC2 Instance Profile
    Default: EC2RoleForCodeDeploy
  EC2InstanceTag:
    Type: String
    Description: The tag name for the launched EC2 Instance
    Default: Dev
  ECInstanceProfileName:
    Type: String
    Default: CodeDeployDemoDevInstanceProfile
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-009d6802948d06e52
      InstanceType: t2.micro
      KeyName: !Ref SSHKey
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroups:
        - !Ref SSHSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash -xe
          # Get the latest CloudFormation package
          sudo yum update -y
          sudo yum update -y aws-cfn-bootstrap
          sudo yum install -y ruby wget
          wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install
          chmod +x ./install
          sudo ./install auto
          sudo service codedeploy-agent status
      Tags:
        - Key: Environment
          Value: !Ref EC2InstanceTag
        - Key: Name
          Value: webserver
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Ref ECInstanceProfileName
      Path: "/"
      Roles:
        - !Ref EC2RoleForCodeDeploy
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
Outputs:
  MyInstancePublicIp:
    Description: The public ip address of the launched EC2 instance
    Value: !GetAtt MyInstance.PublicIp
