AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template
Parameters:
  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Default: test1
  AWSManagedCodeDeployoPolicy:
    Type: String
    Description: AWS managed codedeploy role policy
    Default: arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
  EC2InstanceTag:
    Type: String
    Description: The tag name for the launched EC2 Instance
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-009d6802948d06e52
      InstanceType: t2.micro
      KeyName: !Ref SSHKey
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroups:
        - !Ref SSHSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash -xe
          # Get the latest CloudFormation package
          sudo yum update -y
          sudo yum update -y aws-cfn-bootstrap
          sudo yum install -y ruby wget
          wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install
          chmod +x ./install
          sudo ./install auto
          sudo service codedeploy-agent status
      Tags:
        - Key: Environment
          Value: !Ref EC2InstanceTag
        - Key: Name
          Value: webserver
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: CodeDeployDemoInstanceProfile
      Path: "/"
      Roles:
        - !Ref EC2RoleForCodeDeploy
  EC2RoleForCodeDeploy:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2RoleForCodeDeploy
      Description: IAM role for EC2 stance for reading S3 objects
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - !Ref AWSManagedCodeDeployoPolicy
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
Outputs:
  MyInstancePublicIp:
    Description: The public ip address of the launched EC2 instance
    Value: !GetAtt MyInstance.PublicIp
